import 'package:flutter/material.dart';

import 'permissions.dart';

enum ModuleKind { dashboard, catalog, tours, pos, assistant, notifications, sync }

class AppModule {
  const AppModule({
    required this.id,
    required this.label,
    required this.resource,
    required this.section,
    required this.icon,
    required this.kind,
    this.listPath,
    this.createLabel,
    this.prefetchPaths = const [],
  });

  final String id;
  final String label;
  final String resource;
  final String section;
  final IconData icon;
  final ModuleKind kind;
  final String? listPath;
  final String? createLabel;
  final List<String> prefetchPaths;
}

const appModules = <AppModule>[
  AppModule(
    id: 'dashboard',
    label: 'Tableau de bord',
    resource: 'dashboard',
    section: 'ANALYSE',
    icon: Icons.dashboard_outlined,
    kind: ModuleKind.dashboard,
    listPath: '/dashboard/overview',
    prefetchPaths: ['/dashboard/overview'],
  ),
  AppModule(
    id: 'observability',
    label: 'Supervision',
    resource: 'observability',
    section: 'ANALYSE',
    icon: Icons.monitor_heart_outlined,
    kind: ModuleKind.catalog,
    listPath: '/emmapure/observability',
    prefetchPaths: ['/emmapure/observability'],
  ),
  AppModule(
    id: 'ai',
    label: 'IA prédictive',
    resource: 'ai',
    section: 'INTELLIGENCE',
    icon: Icons.auto_awesome_outlined,
    kind: ModuleKind.catalog,
    listPath: '/ai/demand-forecast',
    prefetchPaths: ['/ai/demand-forecast', '/ai/anomalies', '/ai/maintenance-risk'],
  ),
  AppModule(
    id: 'assistant',
    label: 'Assistant',
    resource: 'assistant',
    section: 'INTELLIGENCE',
    icon: Icons.smart_toy_outlined,
    kind: ModuleKind.assistant,
    listPath: '/assistant/sessions',
    prefetchPaths: ['/assistant/sessions'],
  ),
  AppModule(
    id: 'clients',
    label: 'Clients',
    resource: 'clients',
    section: 'ANNUAIRES',
    icon: Icons.people_outline,
    kind: ModuleKind.catalog,
    listPath: '/clients',
    createLabel: 'Nouveau client',
    prefetchPaths: ['/clients'],
  ),
  AppModule(
    id: 'contracts',
    label: 'Contrats',
    resource: 'contracts',
    section: 'CONTRATS',
    icon: Icons.description_outlined,
    kind: ModuleKind.catalog,
    listPath: '/contracts',
    prefetchPaths: ['/contracts', '/contracts/summary', '/contracts/suppliers'],
  ),
  AppModule(
    id: 'orders',
    label: 'Commandes',
    resource: 'orders',
    section: 'COMMANDES',
    icon: Icons.receipt_long_outlined,
    kind: ModuleKind.catalog,
    listPath: '/orders',
    createLabel: 'Nouvelle commande',
    prefetchPaths: ['/orders'],
  ),
  AppModule(
    id: 'pos',
    label: 'Point de vente',
    resource: 'pos',
    section: 'COMMANDES',
    icon: Icons.point_of_sale_outlined,
    kind: ModuleKind.pos,
    listPath: '/pos/sales',
    prefetchPaths: ['/pos/catalog', '/pos/sales'],
  ),
  AppModule(
    id: 'products',
    label: 'Catalogue produits',
    resource: 'products',
    section: 'COMMANDES',
    icon: Icons.inventory_2_outlined,
    kind: ModuleKind.catalog,
    listPath: '/products',
    prefetchPaths: ['/products'],
  ),
  AppModule(
    id: 'pricing',
    label: 'Tarifs et bonus',
    resource: 'pricing',
    section: 'COMMANDES',
    icon: Icons.sell_outlined,
    kind: ModuleKind.catalog,
    listPath: '/pricing-rules',
    prefetchPaths: ['/pricing-rules'],
  ),
  AppModule(
    id: 'stock',
    label: 'Stocks & achats',
    resource: 'stock',
    section: 'ACHATS',
    icon: Icons.warehouse_outlined,
    kind: ModuleKind.catalog,
    listPath: '/stock',
    createLabel: 'Ajuster le stock',
    prefetchPaths: ['/stock', '/stock/locations'],
  ),
  AppModule(
    id: 'packaging',
    label: 'Emballages',
    resource: 'packaging',
    section: 'ACHATS',
    icon: Icons.inventory_outlined,
    kind: ModuleKind.catalog,
    listPath: '/packaging',
    prefetchPaths: ['/packaging', '/packaging/summary', '/packaging/movements'],
  ),
  AppModule(
    id: 'production',
    label: 'Fabrication / OF',
    resource: 'production',
    section: 'FABRICATION',
    icon: Icons.precision_manufacturing_outlined,
    kind: ModuleKind.catalog,
    listPath: '/emmapure/production',
    prefetchPaths: ['/emmapure/production'],
  ),
  AppModule(
    id: 'quality',
    label: 'Contrôle qualité',
    resource: 'quality',
    section: 'FABRICATION',
    icon: Icons.verified_outlined,
    kind: ModuleKind.catalog,
    listPath: '/emmapure/quality',
    prefetchPaths: ['/emmapure/quality'],
  ),
  AppModule(
    id: 'tours',
    label: 'Tournées',
    resource: 'tours',
    section: 'LIVRAISON',
    icon: Icons.local_shipping_outlined,
    kind: ModuleKind.tours,
    listPath: '/tours',
    prefetchPaths: ['/tours'],
  ),
  AppModule(
    id: 'vehicles',
    label: 'Véhicules',
    resource: 'vehicles',
    section: 'LIVRAISON',
    icon: Icons.directions_car_outlined,
    kind: ModuleKind.catalog,
    listPath: '/vehicles',
    prefetchPaths: ['/vehicles'],
  ),
  AppModule(
    id: 'routing',
    label: 'Itinéraires',
    resource: 'routing',
    section: 'LIVRAISON',
    icon: Icons.route_outlined,
    kind: ModuleKind.catalog,
    listPath: '/routing/routes',
    prefetchPaths: ['/routing/routes'],
  ),
  AppModule(
    id: 'deliveries',
    label: 'Livraisons',
    resource: 'deliveries',
    section: 'LIVRAISON',
    icon: Icons.delivery_dining_outlined,
    kind: ModuleKind.catalog,
    listPath: '/deliveries',
    prefetchPaths: ['/deliveries'],
  ),
  AppModule(
    id: 'iot',
    label: 'Capteurs IoT',
    resource: 'iot',
    section: 'OBJETS CONNECTÉS',
    icon: Icons.sensors_outlined,
    kind: ModuleKind.catalog,
    listPath: '/iot/sensors',
    prefetchPaths: ['/iot/sensors', '/iot/telemetry/vehicles', '/iot/fountains'],
  ),
  AppModule(
    id: 'payments',
    label: 'Factures & paiements',
    resource: 'payments',
    section: 'FACTURES',
    icon: Icons.payments_outlined,
    kind: ModuleKind.catalog,
    listPath: '/payments',
    createLabel: 'Encaisser',
    prefetchPaths: ['/payments'],
  ),
  AppModule(
    id: 'finance',
    label: 'Comptabilité',
    resource: 'finance',
    section: 'FACTURES',
    icon: Icons.account_balance_outlined,
    kind: ModuleKind.catalog,
    listPath: '/finance/movements',
    prefetchPaths: ['/finance/summary', '/finance/accounts', '/finance/movements', '/finance/categories'],
  ),
  AppModule(
    id: 'ecarts',
    label: 'Écarts et clôtures',
    resource: 'ecarts',
    section: 'FACTURES',
    icon: Icons.balance_outlined,
    kind: ModuleKind.catalog,
    listPath: '/ecarts',
    prefetchPaths: ['/ecarts', '/ecarts/cash-closings'],
  ),
  AppModule(
    id: 'recouvrement',
    label: 'Recouvrement',
    resource: 'recouvrement',
    section: 'FACTURES',
    icon: Icons.request_quote_outlined,
    kind: ModuleKind.catalog,
    listPath: '/recouvrement',
    prefetchPaths: ['/recouvrement'],
  ),
  AppModule(
    id: 'loyalty',
    label: 'Fidélité',
    resource: 'loyalty',
    section: 'COMMERCE',
    icon: Icons.card_giftcard_outlined,
    kind: ModuleKind.catalog,
    listPath: '/emmapure/loyalty',
    prefetchPaths: ['/emmapure/loyalty'],
  ),
  AppModule(
    id: 'consignes',
    label: 'Consignes',
    resource: 'consignes',
    section: 'COMMERCE',
    icon: Icons.recycling_outlined,
    kind: ModuleKind.catalog,
    listPath: '/consignes',
    prefetchPaths: ['/consignes'],
  ),
  AppModule(
    id: 'marketplace',
    label: 'Marketplace B2B',
    resource: 'marketplace',
    section: 'COMMERCE',
    icon: Icons.storefront_outlined,
    kind: ModuleKind.catalog,
    listPath: '/marketplace/quote-requests',
    prefetchPaths: ['/marketplace/quote-requests'],
  ),
  AppModule(
    id: 'esg',
    label: 'Durabilité / ESG',
    resource: 'esg',
    section: 'DURABILITÉ',
    icon: Icons.eco_outlined,
    kind: ModuleKind.catalog,
    listPath: '/esg/indicators',
    prefetchPaths: ['/esg/indicators', '/esg/dashboard'],
  ),
  AppModule(
    id: 'hr',
    label: 'Administration RH',
    resource: 'hr',
    section: 'PERSONNEL',
    icon: Icons.badge_outlined,
    kind: ModuleKind.catalog,
    listPath: '/hr/employees',
    prefetchPaths: ['/hr/employees', '/emmapure/shifts'],
  ),
  AppModule(
    id: 'objectives',
    label: 'Objectifs agents',
    resource: 'objectives',
    section: 'PERSONNEL',
    icon: Icons.flag_outlined,
    kind: ModuleKind.catalog,
    listPath: '/activity-objectives',
    prefetchPaths: ['/activity-objectives'],
  ),
  AppModule(
    id: 'activity',
    label: 'Rapports d’activité',
    resource: 'activity',
    section: 'PERSONNEL',
    icon: Icons.assignment_outlined,
    kind: ModuleKind.catalog,
    listPath: '/hr/activity-reports/overview',
    prefetchPaths: ['/hr/activity-reports/overview', '/hr/activity-reports/me'],
  ),
  AppModule(
    id: 'payroll',
    label: 'Paie des agents',
    resource: 'payroll',
    section: 'PERSONNEL',
    icon: Icons.payments_outlined,
    kind: ModuleKind.catalog,
    listPath: '/hr/payroll/periods',
    prefetchPaths: ['/hr/payroll/periods'],
  ),
  AppModule(
    id: 'users',
    label: 'Utilisateurs',
    resource: 'users',
    section: 'PERSONNEL',
    icon: Icons.manage_accounts_outlined,
    kind: ModuleKind.catalog,
    listPath: '/users',
    prefetchPaths: ['/users'],
  ),
  AppModule(
    id: 'security',
    label: 'Centre de sécurité',
    resource: 'security',
    section: 'SÉCURITÉ',
    icon: Icons.security_outlined,
    kind: ModuleKind.catalog,
    listPath: '/security/center/alerts',
    prefetchPaths: ['/security/center/summary', '/security/center/alerts', '/security/center/audit'],
  ),
  AppModule(
    id: 'authorizations',
    label: 'Habilitations',
    resource: 'authorizations',
    section: 'SÉCURITÉ',
    icon: Icons.lock_person_outlined,
    kind: ModuleKind.catalog,
    listPath: '/authorizations/catalog',
    prefetchPaths: ['/authorizations/me', '/authorizations/catalog'],
  ),
  AppModule(
    id: 'integrations',
    label: 'API & webhooks',
    resource: 'integrations',
    section: 'PARAMÉTRAGE',
    icon: Icons.hub_outlined,
    kind: ModuleKind.catalog,
    listPath: '/integrations/api-keys',
    prefetchPaths: ['/integrations/api-keys', '/integrations/webhooks'],
  ),
  AppModule(
    id: 'notifications',
    label: 'Notifications',
    resource: 'notifications',
    section: 'PARAMÉTRAGE',
    icon: Icons.notifications_outlined,
    kind: ModuleKind.notifications,
    listPath: '/notifications',
    prefetchPaths: ['/notifications', '/notifications/unread-count'],
  ),
  AppModule(
    id: 'sync',
    label: 'Synchronisation',
    resource: 'dashboard',
    section: 'PARAMÉTRAGE',
    icon: Icons.cloud_sync_outlined,
    kind: ModuleKind.sync,
  ),
];

List<AppModule> modulesFor(String role, Map<String, List<String>>? matrix) {
  return appModules.where((m) {
    if (m.id == 'sync') return true;
    return can(role, m.resource, 'read', matrix);
  }).toList();
}
